/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatsIndexRouteImport } from './routes/chats/index'
import { Route as ChatsChatIdRouteImport } from './routes/chats/$chatId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ChatsGroupCreateRouteImport } from './routes/chats/group/create'

const ChatsIndexRoute = ChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsChatIdRoute = ChatsChatIdRouteImport.update({
  id: '/chats/$chatId',
  path: '/chats/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsGroupCreateRoute = ChatsGroupCreateRouteImport.update({
  id: '/chats/group/create',
  path: '/chats/group/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats': typeof ChatsIndexRoute
  '/chats/group/create': typeof ChatsGroupCreateRoute
}
export interface FileRoutesByTo {
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats': typeof ChatsIndexRoute
  '/chats/group/create': typeof ChatsGroupCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/chats/$chatId': typeof ChatsChatIdRoute
  '/chats/': typeof ChatsIndexRoute
  '/chats/group/create': typeof ChatsGroupCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth/login'
    | '/auth/register'
    | '/chats/$chatId'
    | '/chats'
    | '/chats/group/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/login'
    | '/auth/register'
    | '/chats/$chatId'
    | '/chats'
    | '/chats/group/create'
  id:
    | '__root__'
    | '/auth/login'
    | '/auth/register'
    | '/chats/$chatId'
    | '/chats/'
    | '/chats/group/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ChatsChatIdRoute: typeof ChatsChatIdRoute
  ChatsIndexRoute: typeof ChatsIndexRoute
  ChatsGroupCreateRoute: typeof ChatsGroupCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chats/': {
      id: '/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/$chatId': {
      id: '/chats/$chatId'
      path: '/chats/$chatId'
      fullPath: '/chats/$chatId'
      preLoaderRoute: typeof ChatsChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats/group/create': {
      id: '/chats/group/create'
      path: '/chats/group/create'
      fullPath: '/chats/group/create'
      preLoaderRoute: typeof ChatsGroupCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ChatsChatIdRoute: ChatsChatIdRoute,
  ChatsIndexRoute: ChatsIndexRoute,
  ChatsGroupCreateRoute: ChatsGroupCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
